/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GradientButton {
    'color': string;
    'colorHover': string;
    'text': string;
  }
  interface GradientButtonAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'colorHover'?: string;
    'text'?: string;
  }

  interface InputTag {
    'color': string;
    'placeholder': string;
  }
  interface InputTagAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'placeholder'?: string;
  }

  interface SliderComponent {
    'color': string;
    'max': number;
    'min': number;
  }
  interface SliderComponentAttributes extends StencilHTMLAttributes {
    'color'?: string;
    'max'?: number;
    'min'?: number;
  }

  interface WelcomeComponent {}
  interface WelcomeComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'GradientButton': Components.GradientButton;
    'InputTag': Components.InputTag;
    'SliderComponent': Components.SliderComponent;
    'WelcomeComponent': Components.WelcomeComponent;
  }

  interface StencilIntrinsicElements {
    'gradient-button': Components.GradientButtonAttributes;
    'input-tag': Components.InputTagAttributes;
    'slider-component': Components.SliderComponentAttributes;
    'welcome-component': Components.WelcomeComponentAttributes;
  }


  interface HTMLGradientButtonElement extends Components.GradientButton, HTMLStencilElement {}
  var HTMLGradientButtonElement: {
    prototype: HTMLGradientButtonElement;
    new (): HTMLGradientButtonElement;
  };

  interface HTMLInputTagElement extends Components.InputTag, HTMLStencilElement {}
  var HTMLInputTagElement: {
    prototype: HTMLInputTagElement;
    new (): HTMLInputTagElement;
  };

  interface HTMLSliderComponentElement extends Components.SliderComponent, HTMLStencilElement {}
  var HTMLSliderComponentElement: {
    prototype: HTMLSliderComponentElement;
    new (): HTMLSliderComponentElement;
  };

  interface HTMLWelcomeComponentElement extends Components.WelcomeComponent, HTMLStencilElement {}
  var HTMLWelcomeComponentElement: {
    prototype: HTMLWelcomeComponentElement;
    new (): HTMLWelcomeComponentElement;
  };

  interface HTMLElementTagNameMap {
    'gradient-button': HTMLGradientButtonElement
    'input-tag': HTMLInputTagElement
    'slider-component': HTMLSliderComponentElement
    'welcome-component': HTMLWelcomeComponentElement
  }

  interface ElementTagNameMap {
    'gradient-button': HTMLGradientButtonElement;
    'input-tag': HTMLInputTagElement;
    'slider-component': HTMLSliderComponentElement;
    'welcome-component': HTMLWelcomeComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
